from __future__ import annotations

import random
from dataclasses import dataclass
from time import monotonic
from typing import Callable

from screen_behavior.awareness.models import (
    ActivityType,
    ScreenContext,
)
from screen_behavior.pet.config import (
    BEHAVIOR_SPECS,
    BehaviorSpec,
)
from screen_behavior.pet.enums import BaseMood, Behavior, SpecialMood
from screen_behavior.pet.models import PetState


@dataclass(slots=True)
class ExternalSignals:
    """
    Signals generated by systems outside this subgroup.

    We consume the signal but do not implement microphone processing.
    """
    loud_voice_detected: bool = False


@dataclass(slots=True)
class BehaviorDecision:
    behavior: Behavior
    mood: BaseMood
    special_mood: SpecialMood | None
    reason: str
    distracting: bool
    commitment_remaining_seconds: float
    cooldown_remaining_seconds: float


class BehaviorEngine:
    """
    Autonomous behavior scheduler.

    It chooses *intent only*. It does not animate the model or define frame
    timing. Commitment means "the brain intends to stay with this behavior
    for at least this long."
    """

    def __init__(
        self,
        rng: random.Random | None = None,
        clock: Callable[[], float] = monotonic,
        specs: dict[Behavior, BehaviorSpec] | None = None,
    ) -> None:
        self.rng = rng or random.Random()
        self.clock = clock
        self.specs = specs or BEHAVIOR_SPECS

        self._current_behavior: Behavior | None = None
        self._commitment_until: float = 0.0
        self._last_started: dict[Behavior, float] = {}

    def decide(
        self,
        pet: PetState,
        screen: ScreenContext,
        signals: ExternalSignals | None = None,
    ) -> BehaviorDecision:
        signals = signals or ExternalSignals()
        now = self.clock()

        # Play-dead wake-up is intentionally a state transition, not a content event.
        if pet.play_dead_active and signals.loud_voice_detected:
            pet.play_dead_active = False
            pet.mood = BaseMood.SURPRISED
            return self._start(
                pet,
                Behavior.WAVE,
                "loud external wake signal received",
                now,
                force=True,
            )

        if pet.play_dead_active:
            return self._hold_existing(
                pet,
                Behavior.PLAY_DEAD,
                "waiting for external loud-voice signal",
                now,
            )

        urgent = self._urgent_behavior(pet)

        if urgent is not None:
            # Urgent needs may interrupt a less important commitment.
            if self._current_behavior != urgent:
                return self._start(
                    pet,
                    urgent,
                    self._urgent_reason(urgent),
                    now,
                    force=True,
                )

        if (
            self._current_behavior is not None
            and now < self._commitment_until
        ):
            return self._hold_existing(
                pet,
                self._current_behavior,
                "continuing committed autonomous behavior",
                now,
            )

        candidate, reason = self._choose_candidate(
            pet,
            screen,
            now,
        )

        return self._start(
            pet,
            candidate,
            reason,
            now,
        )

    def _urgent_behavior(self, pet: PetState) -> Behavior | None:
        if pet.energy <= 18:
            return Behavior.SLEEP
        if pet.attention <= 18:
            return Behavior.ASK_FOR_ATTENTION
        if pet.hunger >= 80:
            return Behavior.ASK_FOR_ATTENTION
        return None

    @staticmethod
    def _urgent_reason(behavior: Behavior) -> str:
        if behavior == Behavior.SLEEP:
            return "energy is critically low"
        return "a Tamagotchi need is critically low"

    def _choose_candidate(
        self,
        pet: PetState,
        screen: ScreenContext,
        now: float,
    ) -> tuple[Behavior, str]:
        # High-energy affectionate behavior.
        if (
            pet.energy >= 95
            and pet.affection >= 70
            and self.rng.random() < 0.16
            and self._available(Behavior.SEND_KISS, pet, now)
        ):
            return (
                Behavior.SEND_KISS,
                "energy and affection are both very high",
            )

        # Work-aware quiet behavior.
        if screen.user_is_working:
            preferred = [
                Behavior.STUDY_WITH_USER,
                Behavior.SIT_DOWN,
                Behavior.FOLLOW_MOUSE_WITH_EYES,
                Behavior.LOOK_AROUND,
                Behavior.STRETCH,
            ]

            available = [
                b for b in preferred
                if self._available(b, pet, now)
            ]

            if available:
                return (
                    self.rng.choice(available),
                    "user appears to be working; prefer low-distraction behavior",
                )

        # Passive watching for video/gaming.
        if (
            screen.activity in {ActivityType.GAMING, ActivityType.VIDEO}
            and self._available(Behavior.WATCH_SCREEN, pet, now)
            and self.rng.random() < 0.65
        ):
            return (
                Behavior.WATCH_SCREEN,
                f"user appears to be {screen.activity.value}",
            )

        # Rare play-dead behavior.
        if (
            pet.energy >= 45
            and pet.attention >= 35
            and self._available(Behavior.PLAY_DEAD, pet, now)
            and self.rng.random() < 0.02
        ):
            return (
                Behavior.PLAY_DEAD,
                "rare autonomous play-dead behavior",
            )

        normal = [
            Behavior.IDLE,
            Behavior.LOOK_AROUND,
            Behavior.SIT_DOWN,
            Behavior.FOLLOW_MOUSE_WITH_EYES,
            Behavior.WAVE,
            Behavior.STRETCH,
            Behavior.WALK_AROUND_CORNER,
            Behavior.DANCE,
        ]

        available = [
            b for b in normal
            if self._available(b, pet, now)
        ]

        if not available:
            return Behavior.IDLE, "no other autonomous behavior is available"

        return (
            self.rng.choice(available),
            "normal autonomous behavior selection",
        )

    def _available(
        self,
        behavior: Behavior,
        pet: PetState,
        now: float,
    ) -> bool:
        spec = self.specs[behavior]

        if pet.energy < spec.min_energy:
            return False

        last_started = self._last_started.get(behavior)

        if last_started is None:
            return True

        return now >= last_started + spec.cooldown_seconds

    def _start(
        self,
        pet: PetState,
        behavior: Behavior,
        reason: str,
        now: float,
        force: bool = False,
    ) -> BehaviorDecision:
        spec = self.specs[behavior]

        if not force and not self._available(behavior, pet, now):
            behavior = Behavior.IDLE
            spec = self.specs[behavior]
            reason = "requested behavior was unavailable; falling back to idle"

        if self._current_behavior != behavior:
            pet.energy = max(0.0, pet.energy - spec.energy_cost)
            pet.current_behavior = behavior
            self._current_behavior = behavior
            self._commitment_until = now + spec.commitment_seconds
            self._last_started[behavior] = now

            if behavior == Behavior.PLAY_DEAD:
                pet.play_dead_active = True

        return self._decision(
            pet,
            behavior,
            reason,
            now,
        )

    def _hold_existing(
        self,
        pet: PetState,
        behavior: Behavior,
        reason: str,
        now: float,
    ) -> BehaviorDecision:
        pet.current_behavior = behavior
        self._current_behavior = behavior
        return self._decision(
            pet,
            behavior,
            reason,
            now,
        )

    def _decision(
        self,
        pet: PetState,
        behavior: Behavior,
        reason: str,
        now: float,
    ) -> BehaviorDecision:
        spec = self.specs[behavior]

        last_started = self._last_started.get(behavior, now)
        cooldown_remaining = max(
            0.0,
            last_started + spec.cooldown_seconds - now,
        )

        commitment_remaining = max(
            0.0,
            self._commitment_until - now,
        )

        return BehaviorDecision(
            behavior=behavior,
            mood=pet.mood,
            special_mood=pet.special_mood,
            reason=reason,
            distracting=spec.distracting,
            commitment_remaining_seconds=commitment_remaining,
            cooldown_remaining_seconds=cooldown_remaining,
        )
