from __future__ import annotations

import random
from dataclasses import dataclass, field, replace
from time import monotonic
from typing import Callable

from screen_behavior.awareness.models import ScreenContext
from screen_behavior.pet.config import (
    BEHAVIOR_SPECS,
    BehaviorSpec,
)
from screen_behavior.pet.distraction import DistractionBudget
from screen_behavior.pet.enums import BaseMood, Behavior, SpecialMood
from screen_behavior.pet.memory import BehaviorMemory, MemorySnapshot
from screen_behavior.pet.models import PetState
from screen_behavior.pet.utility import (
    BehaviorScore,
    PreferenceBonus,
    UtilityScorer,
    build_context,
)
from screen_behavior.pet.utility_config import BehaviorUtilityConfig


@dataclass(slots=True)
class ExternalSignals:
    """
    Signals generated by systems outside this subgroup.

    We consume the signal but do not implement microphone processing.
    """
    loud_voice_detected: bool = False


@dataclass(slots=True)
class BehaviorDecision:
    behavior: Behavior
    mood: BaseMood
    special_mood: SpecialMood | None
    reason: str
    distracting: bool
    commitment_remaining_seconds: float
    cooldown_remaining_seconds: float
    distraction_budget: float = 100.0

    # --- Debugging / tuning (optional for consumers) -----------------------
    # Which stage decided: "utility", "commitment", "urgent", "sleep",
    # "play_dead", or "fallback".
    source: str = "utility"
    # Utility of every eligible behavior this decision (utility source only).
    behavior_scores: dict[Behavior, float] = field(default_factory=dict)
    # Labeled points behind the chosen behavior's score.
    score_breakdown: dict[str, float] = field(default_factory=dict)
    # The strong candidates the final pick was drawn from.
    candidates: list[Behavior] = field(default_factory=list)


class BehaviorEngine:
    """
    Autonomous behavior scheduler.

    It chooses *intent only*. It does not animate the model or define frame
    timing. Commitment means "the brain intends to stay with this behavior
    for at least this long."

    Decision pipeline (first stage that applies wins):
      1. play-dead wake / timeout / hold
      2. stay asleep until rested
      3. urgent biological needs (may interrupt a commitment)
      4. commitment to the current behavior
      5. hard eligibility (min energy, cooldown, distraction budget)
      6. utility scoring (pet/utility.py, tuned in pet/utility_config.py)
      7. controlled variation among strong candidates
    """

    def __init__(
        self,
        rng: random.Random | None = None,
        clock: Callable[[], float] = monotonic,
        specs: dict[Behavior, BehaviorSpec] | None = None,
        budget: DistractionBudget | None = None,
        memory: BehaviorMemory | None = None,
        near_best_margin: float | None = None,
        play_dead_max_seconds: float | None = None,
        sleep_until_energy: float | None = None,
        utility_config: BehaviorUtilityConfig | None = None,
        preference: PreferenceBonus | None = None,
    ) -> None:
        config = utility_config or BehaviorUtilityConfig()
        if near_best_margin is not None:
            config = replace(config, near_best_margin=near_best_margin)
        self.config = config
        self.urgent = config.urgent

        self.rng = rng or random.Random()
        self.clock = clock
        self.specs = specs or BEHAVIOR_SPECS
        self.budget = budget or DistractionBudget()
        self.memory = memory or BehaviorMemory(history_size=config.history_size)
        self.scorer = UtilityScorer(config, preference)

        self.play_dead_max_seconds = (
            play_dead_max_seconds
            if play_dead_max_seconds is not None
            else self.urgent.play_dead_max_seconds
        )
        self.sleep_until_energy = (
            sleep_until_energy
            if sleep_until_energy is not None
            else self.urgent.sleep_until_energy
        )

        self._last_decide: float | None = None
        self._current_behavior: Behavior | None = None
        self._commitment_until: float = 0.0

    def decide(
        self,
        pet: PetState,
        screen: ScreenContext,
        signals: ExternalSignals | None = None,
    ) -> BehaviorDecision:
        signals = signals or ExternalSignals()
        now = self.clock()

        if self._last_decide is not None:
            self.budget.tick(screen, now - self._last_decide)
        self._last_decide = now

        # Play-dead wake-up is intentionally a state transition, not a content event.
        if pet.play_dead_active and signals.loud_voice_detected:
            pet.play_dead_active = False
            pet.mood = BaseMood.SURPRISED
            return self._start(
                pet,
                Behavior.WAVE,
                "loud external wake signal received",
                now,
                force=True,
                source="play_dead",
            )

        # Nobody yelled: buddy gets bored of playing dead and gets up.
        started = self.memory.last_started(Behavior.PLAY_DEAD)
        if (
            pet.play_dead_active
            and started is not None
            and now - started >= self.play_dead_max_seconds
        ):
            pet.play_dead_active = False
            return self._start(
                pet,
                Behavior.LOOK_AROUND,
                "nobody came; got up from playing dead",
                now,
                force=True,
                source="play_dead",
            )

        if pet.play_dead_active:
            return self._hold_existing(
                pet,
                Behavior.PLAY_DEAD,
                "waiting for external loud-voice signal",
                now,
                source="play_dead",
            )

        # Once asleep, stay asleep until properly rested. Without this, buddy
        # naps 20s, wakes at energy 19, drains, and naps again all day.
        if (
            self._current_behavior == Behavior.SLEEP
            and pet.energy < self.sleep_until_energy
        ):
            return self._hold_existing(
                pet,
                Behavior.SLEEP,
                "sleeping until rested",
                now,
                source="sleep",
            )

        urgent = self._urgent_behavior(pet)

        if urgent is not None:
            reason = self._urgent_reason(urgent)

            # Asked for attention and got ignored: sulk instead of nagging.
            if (
                urgent == Behavior.ASK_FOR_ATTENTION
                and self.memory.recently_ignored(now)
            ):
                urgent = Behavior.SIT_DOWN
                reason = "was ignored; sulking instead of asking again"

            # Urgent needs may interrupt a less important commitment.
            if self._current_behavior != urgent:
                return self._start(
                    pet,
                    urgent,
                    reason,
                    now,
                    force=True,
                    source="urgent",
                )

        if (
            self._current_behavior is not None
            and now < self._commitment_until
        ):
            return self._hold_existing(
                pet,
                self._current_behavior,
                "continuing committed autonomous behavior",
                now,
                source="commitment",
            )

        return self._choose(pet, screen, now)

    # --- urgent needs ------------------------------------------------------

    def _urgent_behavior(self, pet: PetState) -> Behavior | None:
        u = self.urgent
        if pet.energy <= u.sleep_at_energy:
            return Behavior.SLEEP
        if pet.attention <= u.attention_critical:
            return Behavior.ASK_FOR_ATTENTION
        if pet.hunger >= u.hunger_critical:
            return Behavior.ASK_FOR_ATTENTION
        return None

    @staticmethod
    def _urgent_reason(behavior: Behavior) -> str:
        if behavior == Behavior.SLEEP:
            return "energy is critically low"
        return "a Tamagotchi need is critically low"

    # --- utility selection --------------------------------------------------

    def _choose(
        self,
        pet: PetState,
        screen: ScreenContext,
        now: float,
    ) -> BehaviorDecision:
        eligible = [b for b in self.specs if self._available(b, pet, now)]
        if not eligible:
            return self._start(
                pet,
                Behavior.IDLE,
                "no other autonomous behavior is available",
                now,
                force=True,
                source="fallback",
            )

        scored = self._score(pet, screen, now, eligible)
        chosen, strong = self.scorer.select(scored, self.rng)

        return self._start(
            pet,
            chosen.behavior,
            chosen.reason,
            now,
            source="utility",
            scores={s.behavior: round(s.score, 1) for s in scored},
            breakdown=chosen.breakdown.rounded(),
            candidates=[s.behavior for s in strong],
        )

    def _score(
        self,
        pet: PetState,
        screen: ScreenContext,
        now: float,
        behaviors,
    ) -> list[BehaviorScore]:
        context = build_context(
            pet,
            screen,
            budget_fraction=self.budget.value / self.budget.config.max_budget,
            now=now,
        )
        return self.scorer.score_all(
            behaviors, self.specs, context, self.memory, self.rng,
        )

    def score_all(
        self,
        pet: PetState,
        screen: ScreenContext,
        now: float | None = None,
    ) -> list[BehaviorScore]:
        """Every behavior's utility, highest first (ignores eligibility)."""
        now = self.clock() if now is None else now
        return self._score(pet, screen, now, list(self.specs))

    # --- memory access --------------------------------------------------------

    def record_interaction(self) -> None:
        """The user interacted with buddy (petting, feeding, etc.)."""
        self.memory.record_interaction(self.clock())

    def memory_snapshot(self) -> MemorySnapshot:
        return self.memory.snapshot(
            self.clock(),
            self.config.recent_distracting_window_seconds,
        )

    # --- hard eligibility -------------------------------------------------

    def _available(
        self,
        behavior: Behavior,
        pet: PetState,
        now: float,
    ) -> bool:
        spec = self.specs[behavior]

        if pet.energy < spec.min_energy:
            return False

        # Impossible state: not tired enough to fall asleep.
        if (
            behavior == Behavior.SLEEP
            and pet.energy >= self.urgent.nap_below_energy
        ):
            return False

        if not self.budget.can_afford(behavior):
            return False

        last_started = self.memory.last_started(behavior)
        if last_started is None:
            return True

        return now >= last_started + spec.cooldown_seconds

    # --- starting / holding -----------------------------------------------

    def _start(
        self,
        pet: PetState,
        behavior: Behavior,
        reason: str,
        now: float,
        force: bool = False,
        source: str = "utility",
        scores: dict[Behavior, float] | None = None,
        breakdown: dict[str, float] | None = None,
        candidates: list[Behavior] | None = None,
    ) -> BehaviorDecision:
        spec = self.specs[behavior]

        if not force and not self._available(behavior, pet, now):
            behavior = Behavior.IDLE
            spec = self.specs[behavior]
            reason = "requested behavior was unavailable; falling back to idle"
            source = "fallback"

        if self._current_behavior != behavior:
            # Costs are charged only when a behavior actually starts.
            pet.energy = max(0.0, pet.energy - spec.energy_cost)
            pet.current_behavior = behavior
            self._current_behavior = behavior
            self._commitment_until = now + spec.commitment_seconds
            self.budget.spend(behavior)
            self.memory.record_behavior(behavior, now, spec.distracting)

            if behavior == Behavior.PLAY_DEAD:
                pet.play_dead_active = True

        return self._decision(
            pet,
            behavior,
            reason,
            now,
            source=source,
            scores=scores,
            breakdown=breakdown,
            candidates=candidates,
        )

    def _hold_existing(
        self,
        pet: PetState,
        behavior: Behavior,
        reason: str,
        now: float,
        source: str = "commitment",
    ) -> BehaviorDecision:
        pet.current_behavior = behavior
        self._current_behavior = behavior
        return self._decision(pet, behavior, reason, now, source=source)

    def _decision(
        self,
        pet: PetState,
        behavior: Behavior,
        reason: str,
        now: float,
        source: str = "utility",
        scores: dict[Behavior, float] | None = None,
        breakdown: dict[str, float] | None = None,
        candidates: list[Behavior] | None = None,
    ) -> BehaviorDecision:
        spec = self.specs[behavior]

        last_started = self.memory.last_started(behavior)
        if last_started is None:
            last_started = now
        cooldown_remaining = max(
            0.0,
            last_started + spec.cooldown_seconds - now,
        )

        commitment_remaining = max(
            0.0,
            self._commitment_until - now,
        )

        return BehaviorDecision(
            behavior=behavior,
            mood=pet.mood,
            special_mood=pet.special_mood,
            reason=reason,
            distracting=spec.distracting,
            commitment_remaining_seconds=commitment_remaining,
            cooldown_remaining_seconds=cooldown_remaining,
            distraction_budget=self.budget.value,
            source=source,
            behavior_scores=scores or {},
            score_breakdown=breakdown or {},
            candidates=candidates or [],
        )
