from __future__ import annotations

import random
from dataclasses import dataclass
from time import monotonic
from typing import Callable

from screen_behavior.awareness.models import ScreenContext
from screen_behavior.pet.config import (
    BEHAVIOR_SPECS,
    BehaviorSpec,
)
from screen_behavior.pet.distraction import DistractionBudget
from screen_behavior.pet.enums import BaseMood, Behavior, SpecialMood
from screen_behavior.pet.memory import BehaviorMemory, MemorySnapshot
from screen_behavior.pet.models import PetState
from screen_behavior.pet.utility import (
    ScoredBehavior,
    build_context,
    score_behavior,
)


@dataclass(slots=True)
class ExternalSignals:
    """
    Signals generated by systems outside this subgroup.

    We consume the signal but do not implement microphone processing.
    """
    loud_voice_detected: bool = False


@dataclass(slots=True)
class BehaviorDecision:
    behavior: Behavior
    mood: BaseMood
    special_mood: SpecialMood | None
    reason: str
    distracting: bool
    commitment_remaining_seconds: float
    cooldown_remaining_seconds: float
    distraction_budget: float = 100.0


class BehaviorEngine:
    """
    Autonomous behavior scheduler.

    It chooses *intent only*. It does not animate the model or define frame
    timing. Commitment means "the brain intends to stay with this behavior
    for at least this long."
    """

    def __init__(
        self,
        rng: random.Random | None = None,
        clock: Callable[[], float] = monotonic,
        specs: dict[Behavior, BehaviorSpec] | None = None,
        budget: DistractionBudget | None = None,
        memory: BehaviorMemory | None = None,
        near_best_margin: float = 0.12,
        play_dead_max_seconds: float = 90.0,
        sleep_until_energy: float = 60.0,
    ) -> None:
        self.rng = rng or random.Random()
        self.clock = clock
        self.specs = specs or BEHAVIOR_SPECS
        self.budget = budget or DistractionBudget()
        self.memory = memory or BehaviorMemory()
        self._last_decide: float | None = None
        self.near_best_margin = near_best_margin
        self.play_dead_max_seconds = play_dead_max_seconds
        self.sleep_until_energy = sleep_until_energy

        self._current_behavior: Behavior | None = None
        self._commitment_until: float = 0.0
        self._last_started: dict[Behavior, float] = {}

    def decide(
        self,
        pet: PetState,
        screen: ScreenContext,
        signals: ExternalSignals | None = None,
    ) -> BehaviorDecision:
        signals = signals or ExternalSignals()
        now = self.clock()

        if self._last_decide is not None:
            self.budget.tick(screen, now - self._last_decide)
        self._last_decide = now

        # Play-dead wake-up is intentionally a state transition, not a content event.
        if pet.play_dead_active and signals.loud_voice_detected:
            pet.play_dead_active = False
            pet.mood = BaseMood.SURPRISED
            return self._start(
                pet,
                Behavior.WAVE,
                "loud external wake signal received",
                now,
                force=True,
            )

        # Nobody yelled: buddy gets bored of playing dead and gets up.
        started = self._last_started.get(Behavior.PLAY_DEAD)
        if (
            pet.play_dead_active
            and started is not None
            and now - started >= self.play_dead_max_seconds
        ):
            pet.play_dead_active = False
            return self._start(
                pet,
                Behavior.LOOK_AROUND,
                "nobody came; got up from playing dead",
                now,
                force=True,
            )

        if pet.play_dead_active:
            return self._hold_existing(
                pet,
                Behavior.PLAY_DEAD,
                "waiting for external loud-voice signal",
                now,
            )

        # Once asleep, stay asleep until properly rested. Without this, buddy
        # naps 20s, wakes at energy 19, drains, and naps again all day.
        if (
            self._current_behavior == Behavior.SLEEP
            and pet.energy < self.sleep_until_energy
        ):
            return self._hold_existing(
                pet,
                Behavior.SLEEP,
                "sleeping until rested",
                now,
            )

        urgent = self._urgent_behavior(pet)

        if urgent is not None:
            reason = self._urgent_reason(urgent)

            # Asked for attention and got ignored: sulk instead of nagging.
            if (
                urgent == Behavior.ASK_FOR_ATTENTION
                and self.memory.recently_ignored(now)
            ):
                urgent = Behavior.SIT_DOWN
                reason = "was ignored; sulking instead of asking again"

            # Urgent needs may interrupt a less important commitment.
            if self._current_behavior != urgent:
                return self._start(
                    pet,
                    urgent,
                    reason,
                    now,
                    force=True,
                )

        if (
            self._current_behavior is not None
            and now < self._commitment_until
        ):
            return self._hold_existing(
                pet,
                self._current_behavior,
                "continuing committed autonomous behavior",
                now,
            )

        candidate, reason = self._choose_candidate(
            pet,
            screen,
            now,
        )

        return self._start(
            pet,
            candidate,
            reason,
            now,
        )

    def _urgent_behavior(self, pet: PetState) -> Behavior | None:
        if pet.energy <= 18:
            return Behavior.SLEEP
        if pet.attention <= 18:
            return Behavior.ASK_FOR_ATTENTION
        if pet.hunger >= 80:
            return Behavior.ASK_FOR_ATTENTION
        return None

    @staticmethod
    def _urgent_reason(behavior: Behavior) -> str:
        if behavior == Behavior.SLEEP:
            return "energy is critically low"
        return "a Tamagotchi need is critically low"

    def _choose_candidate(
        self,
        pet: PetState,
        screen: ScreenContext,
        now: float,
    ) -> tuple[Behavior, str]:
        """
        Utility scoring: every eligible behavior gets a score from needs,
        mood, user context, distraction budget, and memory. The best wins.

        Behaviors within `near_best_margin` of the top score count as
        equally good, and one is picked at random, so buddy isn't robotic.
        """
        scored = self.score_all(pet, screen, now)
        eligible = [s for s in scored if self._available(s.behavior, pet, now)]

        if not eligible:
            return Behavior.IDLE, "no other autonomous behavior is available"

        best = eligible[0].score
        near_best = [
            s for s in eligible
            if s.score >= best - self.near_best_margin
        ]
        chosen_behavior = self.rng.choice([s.behavior for s in near_best])
        chosen = next(s for s in near_best if s.behavior == chosen_behavior)

        return chosen.behavior, chosen.reason

    def score_all(
        self,
        pet: PetState,
        screen: ScreenContext,
        now: float | None = None,
    ) -> list[ScoredBehavior]:
        """All behaviors, highest utility first (ignores eligibility)."""
        now = self.clock() if now is None else now
        context = build_context(
            pet,
            screen,
            budget_fraction=(
                self.budget.value / self.budget.config.max_budget
            ),
            recently_ignored=self.memory.recently_ignored(now),
            whim=self.rng.random(),
        )
        scored = [
            score_behavior(
                behavior,
                context,
                distracting=self.specs[behavior].distracting,
                repetitive=self.memory.is_repetitive(behavior),
            )
            for behavior in self.specs
        ]
        scored.sort(key=lambda s: s.score, reverse=True)
        return scored

    def record_interaction(self) -> None:
        """The user interacted with buddy (petting, feeding, etc.)."""
        self.memory.record_interaction(self.clock())

    def memory_snapshot(self) -> MemorySnapshot:
        return self.memory.snapshot(self.clock())

    def _available(
        self,
        behavior: Behavior,
        pet: PetState,
        now: float,
    ) -> bool:
        spec = self.specs[behavior]

        if pet.energy < spec.min_energy:
            return False

        if not self.budget.can_afford(behavior):
            return False

        last_started = self._last_started.get(behavior)

        if last_started is None:
            return True

        return now >= last_started + spec.cooldown_seconds

    def _start(
        self,
        pet: PetState,
        behavior: Behavior,
        reason: str,
        now: float,
        force: bool = False,
    ) -> BehaviorDecision:
        spec = self.specs[behavior]

        if not force and not self._available(behavior, pet, now):
            behavior = Behavior.IDLE
            spec = self.specs[behavior]
            reason = "requested behavior was unavailable; falling back to idle"

        if self._current_behavior != behavior:
            pet.energy = max(0.0, pet.energy - spec.energy_cost)
            pet.current_behavior = behavior
            self._current_behavior = behavior
            self._commitment_until = now + spec.commitment_seconds
            self._last_started[behavior] = now
            self.budget.spend(behavior)
            self.memory.record_behavior(behavior, now)

            if behavior == Behavior.PLAY_DEAD:
                pet.play_dead_active = True

        return self._decision(
            pet,
            behavior,
            reason,
            now,
        )

    def _hold_existing(
        self,
        pet: PetState,
        behavior: Behavior,
        reason: str,
        now: float,
    ) -> BehaviorDecision:
        pet.current_behavior = behavior
        self._current_behavior = behavior
        return self._decision(
            pet,
            behavior,
            reason,
            now,
        )

    def _decision(
        self,
        pet: PetState,
        behavior: Behavior,
        reason: str,
        now: float,
    ) -> BehaviorDecision:
        spec = self.specs[behavior]

        last_started = self._last_started.get(behavior, now)
        cooldown_remaining = max(
            0.0,
            last_started + spec.cooldown_seconds - now,
        )

        commitment_remaining = max(
            0.0,
            self._commitment_until - now,
        )

        return BehaviorDecision(
            behavior=behavior,
            mood=pet.mood,
            special_mood=pet.special_mood,
            reason=reason,
            distracting=spec.distracting,
            commitment_remaining_seconds=commitment_remaining,
            cooldown_remaining_seconds=cooldown_remaining,
            distraction_budget=self.budget.value,
        )
